sudo: required
language: generic
services:
  - docker 

before_install:
  - docker build -t mskramst/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true mskramst/docker-react npm run test